[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install -r requirements.txt && python railway_start.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
PYTHON_VERSION = "3.12"
